### ISSUE TITLE
Add the pod!

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/pod-22.P3.2-portfolio#13]
Currently, then repository has members of the MLH team on it, but you should replace them with members of the pod.

You can update information in `_data/fellows.yml`

You should work on:
- [ ] Replacing the images
- [ ] Update the names and locations of each fellow
- [ ] Update the pod number inside of `_config.yml`

**Comment by samarthya-jha** [comment]
For the first task in the issue, we need to replace the images of the pod fellows but since the recent [PR](https://github.com/MLH-Fellowship/pod-22.P3.2-portfolio/pull/15) for the issue [#3 ](https://github.com/MLH-Fellowship/pod-22.P3.2-portfolio/issues/3) removed the profile pictures from the header, so can we add the images in the cards of the fellows? Image attached for reference:

![image](https://user-images.githubusercontent.com/60847738/161926527-a3a50d57-d1af-4777-926a-eb513eb6da83.png)

**Comment by prakharrathi25** [comment]
After discussions with @samarthya-jha, I can say that this looks really good and seems better than putting the images in the header. I think this is the neater way of going about it. Also, it seems that this fix might make issue #12 redundant. Maybe we can close that? @marcnjaramillo what do you think?

**Comment by marcnjaramillo** [comment]
Yes, it can safely be closed. Issue [#12](https://github.com/MLH-Fellowship/pod-22.P3.2-portfolio/issues/12) and issue #13 are very closely related, and typically the profile pictures are moved out of the header anyway.
